# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd05756374068df02e29f38dc340a4b42bb5e0ad602558334408c17eb792d669a63e016f0e26ea0f29a8b86c1e0936aaf309172336e2be71e0a09362bee3c5a

test:
  secret_key_base: 1cd6134e19f932399be7f9f4b683afd8e2394e7dc3c4e8eea0e81caea879f0bc1c14d96cc7ced56448a057c0f8fef8f05622a579a1b4e9257a51d034be1e6f30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
